# Generated by Django 5.1.7 on 2025-03-27 15:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_location_state_profile_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='zip_code',
            field=models.CharField(blank=True, max_length=6, null=True, validators=[django.core.validators.RegexValidator(message='ZIP code must be exactly 6 digits', regex='^\\d{6}$')]),
        ),
    ]
