# Generated by Django 5.1.7 on 2025-03-27 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_location_profile_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='profile',
            new_name='location',
        ),
    ]
