# Generated by Django 5.1.7 on 2025-03-28 04:33

import localflavor.in_.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_profile_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='state',
            field=localflavor.in_.models.INStateField(default='UP', max_length=2),
        ),
    ]
