# Generated by Django 5.1.7 on 2025-04-06 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_rename_photo_profile_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='image',
            new_name='photo',
        ),
    ]
