# Generated by Django 5.1.7 on 2025-04-06 07:04

import users.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_rename_image_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(default='images/default.jpg', null=True, upload_to=users.utils.user_directory_path),
        ),
    ]
